default_platform :ios

platform :ios do
  before_all do
    clear_derived_data(derived_data_path: "./DerivedData")
  end

  desc "Runs setup"
  lane :setup do
    sh "cd .. && xcodegen"
    unless File.exist?("../Pods/Manifest.lock") && FileUtils.cmp("../Podfile.lock", "../Pods/Manifest.lock") then
      cocoapods(verbose: true)
    end
  end
end
